services:
  # Redis for rate limiting and caching
  redis:
    image: redis:7-alpine
    container_name: persona-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --bind 0.0.0.0
    networks:
      - persona-network
    restart: always

  # Chroma Vector Database
  chroma:
    image: chromadb/chroma:latest
    container_name: persona-chroma
    ports:
      - '8000:8000'
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    networks:
      - persona-network
    restart: always

  # Ollama Local LLM with GPU support
  ollama:
    image: ollama/ollama:latest
    container_name: persona-ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - persona-network
    restart: always

  # Persona API
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: persona-api
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - CHROMA_URL=http://chroma:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - RATE_LIMIT_MAX=50
      - RATE_LIMIT_WINDOW_MS=60000
      - LOG_LEVEL=info
    depends_on:
      - redis
      - chroma  
      - ollama
    networks:
      - persona-network
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  persona-network:
    driver: bridge

volumes:
  redis_data:
  chroma_data:
  ollama_data: